batch_size: 512
ckpt_path: null
dataset_name: nsvf
distortion_loss_w: 0
downsample: 1.0
exp_name: Lego
gui: true
half2_opt: false
lr: 0.01
no_save_test: true
num_epochs: 20
perf: true
random_bg: false
ray_sampling_strategy: all_images
root_dir: ./Synthetic_NeRF/Lego
scale: 0.5
split: train
val_only: false
